// Stats.js
// 상태 메시지들을 정의함

module.exports = {
    SUCCESS: 0,
    ERROR_DB_CONNECTION_FAIL: 1,
    ERROR_ID_DUPLICATE: 2,
    ERROR_NO_ID: 3,
    ERROR_WRONG_PASSWORD: 4,
    ERROR_ALREADY_APPLIED: 5,
    ERROR_TASK_NAME_DUPLICATE: 6,
    ERROR_TASK_DATA_TABLE_NAME_DUPLICATE: 7,
    ERROR_NO_TASK: 8,
    ERROR_ALREADY_PARTICIPATING: 9,

}